<?php

namespace OCA\PeppolNext\PonderSource\UBL\Invoice;

/*
    https://docs.peppol.eu/poacc/billing/3.0/codelist/ISO4217/
*/
class CurrencyCode {
    const AED = 'AED'; // UAE Dirham
    const AFN = 'AFN'; // Afghani
    const ALL = 'ALL'; // Lek
    const AMD = 'AMD'; // Armenian Dram
    const ANG = 'ANG'; // Netherlands Antillean Guilder
    const AOA = 'AOA'; // Kwanza
    const ARS = 'ARS'; // Argentine Peso
    const AUD = 'AUD'; // Australian Dollar
    const AWG = 'AWG'; // Aruban Florin
    const AZN = 'AZN'; // Azerbaijan Manat
    const BAM = 'BAM'; // Convertible Mark
    const BBD = 'BBD'; // Barbados Dollar
    const BDT = 'BDT'; // Taka
    const BGN = 'BGN'; // Bulgarian Lev
    const BHD = 'BHD'; // Bahraini Dinar
    const BIF = 'BIF'; // Burundi Franc
    const BMD = 'BMD'; // Bermudian Dollar
    const BND = 'BND'; // Brunei Dollar
    const BOB = 'BOB'; // Boliviano
    const BOV = 'BOV'; // Mvdol
    const BRL = 'BRL'; // Brazilian Real
    const BSD = 'BSD'; // Bahamian Dollar
    const BTN = 'BTN'; // Ngultrum
    const BWP = 'BWP'; // Pula
    const BYN = 'BYN'; // Belarusian Ruble
    const BZD = 'BZD'; // Belize Dollar
    const CAD = 'CAD'; // Canadian Dollar
    const CDF = 'CDF'; // Congolese Franc
    const CHE = 'CHE'; // WIR Euro
    const CHF = 'CHF'; // Swiss Franc
    const CHW = 'CHW'; // WIR Franc
    const CLF = 'CLF'; // Unidad de Fomento
    const CLP = 'CLP'; // Chilean Peso
    const CNY = 'CNY'; // Yuan Renminbi
    const COP = 'COP'; // Colombian Peso
    const COU = 'COU'; // Unidad de Valor Real
    const CRC = 'CRC'; // Costa Rican Colon
    const CUC = 'CUC'; // Peso Convertible
    const CUP = 'CUP'; // Cuban Peso
    const CVE = 'CVE'; // Cabo Verde Escudo
    const CZK = 'CZK'; // Czech Koruna
    const DJF = 'DJF'; // Djibouti Franc
    const DKK = 'DKK'; // Danish Krone
    const DOP = 'DOP'; // Dominican Peso
    const DZD = 'DZD'; // Algerian Dinar
    const EGP = 'EGP'; // Egyptian Pound
    const ERN = 'ERN'; // Nakfa
    const ETB = 'ETB'; // Ethiopian Birr
    const EUR = 'EUR'; // Euro
    const FJD = 'FJD'; // Fiji Dollar
    const FKP = 'FKP'; // Falkland Islands Pound
    const GBP = 'GBP'; // Pound Sterling
    const GEL = 'GEL'; // Lari
    const GHS = 'GHS'; // Ghana Cedi
    const GIP = 'GIP'; // Gibraltar Pound
    const GMD = 'GMD'; // Dalasi
    const GNF = 'GNF'; // Guinean Franc
    const GTQ = 'GTQ'; // Quetzal
    const GYD = 'GYD'; // Guyana Dollar
    const HKD = 'HKD'; // Hong Kong Dollar
    const HNL = 'HNL'; // Lempira
    const HRK = 'HRK'; // Kuna
    const HTG = 'HTG'; // Gourde
    const HUF = 'HUF'; // Forint
    const IDR = 'IDR'; // Rupiah
    const ILS = 'ILS'; // New Israeli Sheqel
    const INR = 'INR'; // Indian Rupee
    const IQD = 'IQD'; // Iraqi Dinar
    const IRR = 'IRR'; // Iranian Rial
    const ISK = 'ISK'; // Iceland Krona
    const JMD = 'JMD'; // Jamaican Dollar
    const JOD = 'JOD'; // Jordanian Dinar
    const JPY = 'JPY'; // Yen
    const KES = 'KES'; // Kenyan Shilling
    const KGS = 'KGS'; // Som
    const KHR = 'KHR'; // Riel
    const KMF = 'KMF'; // Comorian Franc
    const KPW = 'KPW'; // North Korean Won
    const KRW = 'KRW'; // Won
    const KWD = 'KWD'; // Kuwaiti Dinar
    const KYD = 'KYD'; // Cayman Islands Dollar
    const KZT = 'KZT'; // Tenge
    const LAK = 'LAK'; // Lao Kip
    const LBP = 'LBP'; // Lebanese Pound
    const LKR = 'LKR'; // Sri Lanka Rupee
    const LRD = 'LRD'; // Liberian Dollar
    const LSL = 'LSL'; // Loti
    const LYD = 'LYD'; // Libyan Dinar
    const MAD = 'MAD'; // Moroccan Dirham
    const MDL = 'MDL'; // Moldovan Leu
    const MGA = 'MGA'; // Malagasy Ariary
    const MKD = 'MKD'; // Denar
    const MMK = 'MMK'; // Kyat
    const MNT = 'MNT'; // Tugrik
    const MOP = 'MOP'; // Pataca
    const MRU = 'MRU'; // Ouguiya
    const MUR = 'MUR'; // Mauritius Rupee
    const MVR = 'MVR'; // Rufiyaa
    const MWK = 'MWK'; // Malawi Kwacha
    const MXN = 'MXN'; // Mexican Peso
    const MXV = 'MXV'; // Mexican Unidad de Inversion (UDI)
    const MYR = 'MYR'; // Malaysian Ringgit
    const MZN = 'MZN'; // Mozambique Metical
    const NAD = 'NAD'; // Namibia Dollar
    const NGN = 'NGN'; // Naira
    const NIO = 'NIO'; // Cordoba Oro
    const NOK = 'NOK'; // Norwegian Krone
    const NPR = 'NPR'; // Nepalese Rupee
    const NZD = 'NZD'; // New Zealand Dollar
    const OMR = 'OMR'; // Rial Omani
    const PAB = 'PAB'; // Balboa
    const PEN = 'PEN'; // Sol
    const PGK = 'PGK'; // Kina
    const PHP = 'PHP'; // Philippine Piso
    const PKR = 'PKR'; // Pakistan Rupee
    const PLN = 'PLN'; // Zloty
    const PYG = 'PYG'; // Guarani
    const QAR = 'QAR'; // Qatari Rial
    const RON = 'RON'; // Romanian Leu
    const RSD = 'RSD'; // Serbian Dinar
    const RUB = 'RUB'; // Russian Ruble
    const RWF = 'RWF'; // Rwanda Franc
    const SAR = 'SAR'; // Saudi Riyal
    const SBD = 'SBD'; // Solomon Islands Dollar
    const SCR = 'SCR'; // Seychelles Rupee
    const SDG = 'SDG'; // Sudanese Pound
    const SEK = 'SEK'; // Swedish Krona
    const SGD = 'SGD'; // Singapore Dollar
    const SHP = 'SHP'; // Saint Helena Pound
    const SLL = 'SLL'; // Leone
    const SOS = 'SOS'; // Somali Shilling
    const SRD = 'SRD'; // Surinam Dollar
    const SSP = 'SSP'; // South Sudanese Pound
    const STN = 'STN'; // Dobra
    const SVC = 'SVC'; // El Salvador Colon
    const SYP = 'SYP'; // Syrian Pound
    const SZL = 'SZL'; // Lilangeni
    const THB = 'THB'; // Baht
    const TJS = 'TJS'; // Somoni
    const TMT = 'TMT'; // Turkmenistan New Manat
    const TND = 'TND'; // Tunisian Dinar
    const TOP = 'TOP'; // Pa’anga
    const TRY = 'TRY'; // Turkish Lira
    const TTD = 'TTD'; // Trinidad and Tobago Dollar
    const TWD = 'TWD'; // New Taiwan Dollar
    const TZS = 'TZS'; // Tanzanian Shilling
    const UAH = 'UAH'; // Hryvnia
    const UGX = 'UGX'; // Uganda Shilling
    const USD = 'USD'; // US Dollar
    const USN = 'USN'; // US Dollar (Next day)
    const UYI = 'UYI'; // Uruguay Peso en Unidades Indexadas (URUIURUI)
    const UYU = 'UYU'; // Peso Uruguayo
    const UZS = 'UZS'; // Uzbekistan Sum
    const VEF = 'VEF'; // Bolívar
    const VND = 'VND'; // Dong
    const VUV = 'VUV'; // Vatu
    const WST = 'WST'; // Tala
    const XAF = 'XAF'; // CFA Franc BEAC
    const XAG = 'XAG'; // Silver
    const XAU = 'XAU'; // Gold
    const XBA = 'XBA'; // Bond Markets Unit European Composite Unit (EURCO)
    const XBB = 'XBB'; // Bond Markets Unit European Monetary Unit (E.M.U.-6)
    const XBC = 'XBC'; // Bond Markets Unit European Unit of Account 9 (E.U.A.-9)
    const XBD = 'XBD'; // Bond Markets Unit European Unit of Account 17 (E.U.A.-17)
    const XCD = 'XCD'; // East Caribbean Dollar
    const XDR = 'XDR'; // SDR (Special Drawing Right)
    const XOF = 'XOF'; // CFA Franc BCEAO
    const XPD = 'XPD'; // Palladium
    const XPF = 'XPF'; // CFP Franc
    const XPT = 'XPT'; // Platinum
    const XSU = 'XSU'; // Sucre
    const XTS = 'XTS'; // Codes specifically reserved for testing purposes
    const XUA = 'XUA'; // ADB Unit of Account
    const YER = 'YER'; // Yemeni Rial
    const ZAR = 'ZAR'; // Rand
    const ZMW = 'ZMW'; // Zambian Kwacha
    const ZWL = 'ZWL'; // Zimbabwe Dollar
}